swagger: '2.0'
info:
  version: '1.0'
  title: CasaOne Product Reviews API
  description: 'Https endpoint to get product reviews'
  contact: {}
host: '127.0.0.1:3000'
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /reviews:
    get:
      description: ''
      summary: 'http://127.0.0.1:3000/v1/reviews'
      operationId: 'getProductReviews'
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: productId
          in: query
          required: true
          type: string
          description: 'denotes the unique product id'
      responses:
        '200':
          description: ''
          schema:
           $ref: "#/definitions/getReviewResponse"
    put:
      description: ''
      summary: 'http://127.0.0.1:3000/v1/reviews'
      operationId: 'addProductReviews'
      responses:
        '200':
          description: ''
definitions:
  getReviewResponse:
    type: "object"
    properties:
      totalReviews:
        type: "integer"
        format: "int64"
      averageRating:
        type: "integer"
        format: "int64"
      individualRatings:
        type: "array"
        items: 
         $ref: "#/definitions/individualRating"
  individualRating:
    type: "object"
    properties:
      rating:
        type: "number"
        format: "int64"
      count:
        type: "integer"
        format: "int64"